### ISSUE TITLE
Setup Model for Blog post

### ISSUE THREAD

**Issue by christopher-dodge** [christopher-dodge/storie#3]
This work is to create a data model for a blog post.

## Acceptance criteria

- Create a Blog post model in mongoose which has the following properties:
    - Title
    - Date posted
    - Body
    - Author (should be related to another model which describes users)

**Comment by K-Kumar-01** [comment]
I would like to have this issue

**Comment by christopher-dodge** [comment]
> I would like to have this issue

Thank you for your offer but I'm not accepting requests at this time.
